print("              Sandwich making pseudocode")
print('1. Let’s get all the ingredient first. Take tomato sauce in a bowl, 2 piece of sliced cheese, 5-6 sliced cucumber, a slice of chicken breast which is fried and juicy, 2 pieces of bread.')
print('2. Take a piece of bread in plate.')
print('3. Put some tomato sauce on it and spread all over the bread.')
print('4. Put 2/3 piece of cucumber on it.')
print('5. Put a sliced cheese.')
print('6. Put the fried chicken on it.')
print('7. Put 2/3 sliced cucumber.')
print('8. Spread some tomato sauce again.')
print('9. Put a sliced cheese on the top.')
print('10. Lastly, put the last piece of bread and cover all the stuffing.')
print('11. Plug in a sandwich maker.')
print('12. Grease some butter on both side of the sandwich maker.')
print('13. Put the sandwich on the maker.')
print('14. Press it nicely for 20/30 sec.')
print('15. Get your sandwich on your plate & you’ll get a cheesy, juicy sandwich. Enjoy :)')
